//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGallery
    {
        public int Image_ID { get; set; }
        public Nullable<int> Tour_ID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Extra { get; set; }
        public string ExtraTwo { get; set; }
    
        public virtual tblPackage tblPackage { get; set; }
    }
}
